name: ShellCheck

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  shellcheck:
    name: Run ShellCheck
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Find new or modified scripts
      id: find_scripts
      run: |
        # Determine if we're in a pull request or a regular push
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          # Get the list of files changed in the pull request
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.sh$' > scripts-to-check.txt
        else
          # Get the list of files changed in the push
          git diff --name-only HEAD^ HEAD | grep '\.sh$' > scripts-to-check.txt
        fi

        # Check if any scripts were found
        if [ ! -s scripts-to-check.txt ]; then
          echo "No shell scripts to check."
          exit 0
        fi

    - name: Run ShellCheck
      run: |
        while IFS= read -r script; do
          echo "Checking $script"
          shellcheck "$script" || exit 1
        done < scripts-to-check.txt

    - name: Annotate ShellCheck results
      if: failure()
      run: |
        while IFS= read -r script; do
          shellcheck "$script" || true
        done < scripts-to-check.txt

